version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: exemplo_db
    ports:
      - "5432:5432"
    volumes:
      - dados_postgres:/var/lib/postgresql/data

volumes:
  dados_postgres:
